let rule_prefix = "where"
let start_match_pattern = "match"
let start_rewrite_pattern = "rewrite"
let equal = "=="
let not_equal = "!="
let true' = "true"
let false' = "false"
let option_nested = "nested"
let option_strict = "strict"
let pipe_operator = "|"
let arrow = "->"

let separator = "---"
