name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        cd scripts && ./build-base-dependencies-alpine-image.sh
