(executables
 (libraries
  comby
  core
  core_unix.command_unix
  core_unix.filename_unix
  ppx_deriving_yojson
  ppx_deriving_yojson.runtime)
 (preprocess
  (pps ppx_deriving_yojson ppx_let ppx_deriving.show ppx_sexp_conv))
 (modules main)
 (modes byte exe)
 (names main))

(alias
 (name DEFAULT)
 (deps main.exe))

(alias
 (name DEFAULT)
 (deps main.bc))

(install
 (package comby)
 (section bin)
 (files
  (main.exe as comby)))
